"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],NS="http://www.w3.org/2000/svg";
const screens=$$(".screen"),app={settings:{count:5,level:"beginner",lengths:true,faces:false},questions:[],index:0,correct:0,mistakes:[],review:false,answered:false,timer:null,progress:0,selected:null,activeOption:null,spin:0};
const IDS=["front","right","back","left","top","bottom"],NAMES={front:"前",right:"右",back:"後",left:"左",top:"上",bottom:"下"},COLORS={front:"#69b7ff",back:"#9fd3ff",left:"#77d8ab",right:"#43b987",top:"#ffd968",bottom:"#ffe99d"};
const NETS=[[[1,1],[2,1],[3,1],[0,1],[1,0],[1,2]],[[1,1],[2,1],[3,1],[0,1],[2,0],[1,2]],[[1,1],[2,1],[3,1],[0,1],[1,0],[2,2]]];
const BAD=[[[0,1],[1,1],[2,1],[3,1],[1,0],[2,0]],[[0,0],[1,0],[2,0],[0,1],[1,1],[2,1]],[[0,1],[1,1],[2,1],[3,1],[4,1],[2,0]]];
function plan(W,D,H){return[{id:"front",width:W,height:H,parent:null,hingeEdge:null,foldDirection:0,foldOrder:0},{id:"top",width:W,height:D,parent:"front",hingeEdge:"top",foldDirection:1,foldOrder:1},{id:"right",width:D,height:H,parent:"front",hingeEdge:"right",foldDirection:1,foldOrder:2},{id:"bottom",width:W,height:D,parent:"front",hingeEdge:"bottom",foldDirection:-1,foldOrder:3},{id:"left",width:D,height:H,parent:"front",hingeEdge:"left",foldDirection:-1,foldOrder:4},{id:"back",width:W,height:H,parent:"top",hingeEdge:"top",foldDirection:1,foldOrder:5}]}
const shuffle=a=>{const x=[...a];for(let i=x.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x},clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
function show(id){screens.forEach(s=>s.classList.toggle("active",s.id===id));scrollTo(0,0);$("#app").focus()}function val(name){return document.querySelector(`input[name="${name}"]:checked`).value}
function makeQuestion(i,level=app.settings.level){const type=level==="beginner"?"cube":level==="intermediate"?"cuboid":i%2?"cuboid":"cube",dims=type==="cube"?[4,4,4]:[4,3,2],base=plan(...dims),id=`${type}-validated-01`;const correct={id,correct:true,coords:NETS[0],foldPlan:base,failureProgress:1,errorFaces:[],explanation:"6つの面が重ならず、直方体をぴったり囲みます。"},check=validateCompletedCuboid(calculate(correct,1),...dims);document.documentElement.dataset.foldValidation=JSON.stringify({id,...check});if(!check.valid){console.error(`[${id}] 完成形の検証失敗: ${check.reasons.join(" / ")}`);return null}const wrong=BAD.map((coords,j)=>{const fp=base.map(f=>({...f})),target=fp.find(f=>f.id===["back","top","right"][j]);target.foldDirection*=-1;return{id:`${type}-wrong-${j}`,correct:false,coords,foldPlan:fp,failureProgress:[.72,.68,.76][j],errorFaces:[["top","back"],["left","bottom"],["right","back"]][j],explanation:["上の面と後ろの面が重なります。","左の面と下の面が同じ場所へ入ります。","右の面が正しい位置に入らず、立体が閉じません。"][j]}});return{id:`${type}-${i}`,type,dims,validation:check,options:shuffle([correct,...wrong])}}
function begin(review=null){app.review=!!review;app.questions=review?shuffle(review.map(q=>({...q,options:shuffle(q.options)}))):Array.from({length:app.settings.count},(_,i)=>makeQuestion(i)).filter(Boolean);app.index=0;app.correct=0;app.mistakes=[];if(!app.questions.length){console.error("検証に合格した問題がありません");show("homeScreen");return}show("quizScreen");renderQuestion()}
function renderSolid(q){$("#solid").innerHTML='<span class="sf front"></span><span class="sf top"></span><span class="sf side"></span>';$("#dimensions").textContent=(app.settings.faces?"前面・上面・側面　":"")+(app.settings.lengths?`横 ${q.dims[0]} cm　奥行き ${q.dims[1]} cm　高さ ${q.dims[2]} cm`:"")}
function svgEl(name,attrs={}){const e=document.createElementNS(NS,name);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function drawNet(el,o){const xs=o.coords.map(c=>c[0]),ys=o.coords.map(c=>c[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),width=maxX-minX+1,height=maxY-minY+1,margin=.28,svg=svgEl("svg",{viewBox:`${minX-margin} ${minY-margin} ${width+margin*2} ${height+margin*2}`,preserveAspectRatio:"xMidYMid meet","aria-hidden":"true"});o.coords.forEach(([x,y],i)=>{svg.append(svgEl("rect",{x,y,width:1,height:1,class:"net-face"}));if(app.settings.faces){const t=svgEl("text",{x:x+.5,y:y+.52,class:"net-label"});t.textContent=NAMES[IDS[i]];svg.append(t)}});el.append(svg)}
function renderQuestion(){clearInterval(app.timer);app.answered=false;app.progress=0;app.selected=null;app.activeOption=null;const q=app.questions[app.index],total=app.questions.length;$("#questionCount").textContent=`問題 ${app.index+1} / ${total}`;$("#correctCount").textContent=`正解 ${app.correct}`;$("#progressBar").style.width=`${app.index/total*100}%`;$("#feedback").className="feedback";$("#feedback").textContent="";$("#animationPanel").hidden=true;$("#showCorrectBtn").hidden=true;$("#options").innerHTML="";renderSolid(q);q.options.forEach((o,i)=>{const b=document.createElement("button");b.className="option";b.type="button";b.dataset.correct=String(o.correct);b.dataset.optionId=o.id;b.setAttribute("aria-label",`選択肢 ${"ABCD"[i]}`);b.innerHTML=`<span class="option-letter">${"ABCD"[i]}</span><span class="net"></span>`;b.onclick=()=>answer(i);$("#options").append(b);drawNet(b.querySelector(".net"),o)})}
function answer(i){if(app.answered)return;app.answered=true;app.selected=i;const q=app.questions[app.index],o=q.options[i];app.activeOption=o;$$('.option').forEach((b,j)=>{b.disabled=true;if(j===i)b.classList.add(o.correct?"correct":"wrong")});if(o.correct){app.correct++;$("#feedback").textContent="正解！";$("#feedback").classList.add("good");tone(true)}else{app.mistakes.push(q);$("#feedback").textContent="おしい！";$("#feedback").classList.add("bad");tone(false);$("#showCorrectBtn").hidden=false}$("#correctCount").textContent=`正解 ${app.correct}`;$("#animationMessage").textContent=o.correct?"正解の展開図を組み立てます":"ここで正しく組み立てられなくなります";$("#explanation").textContent=o.explanation;$("#animationPanel").hidden=false;buildFold(o);play();$("#animationPanel").scrollIntoView({behavior:"smooth",block:"start"})}
const EPSILON=.001,V=(x=0,y=0,z=0)=>({x,y,z});
function identityMatrix(){return[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]}
function multiplyMatrices(a,b){const r=Array(16).fill(0);for(let row=0;row<4;row++)for(let col=0;col<4;col++)for(let k=0;k<4;k++)r[row*4+col]+=a[row*4+k]*b[k*4+col];return r}
function translationMatrix(x,y,z){const m=identityMatrix();m[3]=x;m[7]=y;m[11]=z;return m}
function rotationAroundAxisMatrix(start,end,angle){let x=end.x-start.x,y=end.y-start.y,z=end.z-start.z;const len=Math.hypot(x,y,z)||1;x/=len;y/=len;z/=len;const c=Math.cos(angle),s=Math.sin(angle),t=1-c,r=[t*x*x+c,t*x*y-s*z,t*x*z+s*y,0,t*x*y+s*z,t*y*y+c,t*y*z-s*x,0,t*x*z-s*y,t*y*z+s*x,t*z*z+c,0,0,0,0,1];return multiplyMatrices(translationMatrix(start.x,start.y,start.z),multiplyMatrices(r,translationMatrix(-start.x,-start.y,-start.z)))}
function transformPoint(m,p){return V(m[0]*p.x+m[1]*p.y+m[2]*p.z+m[3],m[4]*p.x+m[5]*p.y+m[6]*p.z+m[7],m[8]*p.x+m[9]*p.y+m[10]*p.z+m[11])}
function localFoldMatrix(f,parentFace,p){const e=f.hingeEdge,angle=f.foldDirection*Math.PI/2*clamp(p*1.32-(f.foldOrder-1)*.055);let flat,axisStart,axisEnd;if(e==="top"){flat=translationMatrix(0,-f.height,0);axisStart=V(0,0,0);axisEnd=V(parentFace.width,0,0)}if(e==="right"){flat=translationMatrix(parentFace.width,0,0);axisStart=V(parentFace.width,0,0);axisEnd=V(parentFace.width,parentFace.height,0)}if(e==="bottom"){flat=translationMatrix(0,parentFace.height,0);axisStart=V(0,parentFace.height,0);axisEnd=V(parentFace.width,parentFace.height,0)}if(e==="left"){flat=translationMatrix(-f.width,0,0);axisStart=V(0,0,0);axisEnd=V(0,parentFace.height,0)}return multiplyMatrices(rotationAroundAxisMatrix(axisStart,axisEnd,angle),flat)}
function calculate(o,p){const out={};o.foldPlan.slice().sort((a,b)=>a.foldOrder-b.foldOrder).forEach(f=>{const matrix=f.parent?multiplyMatrices(out[f.parent].matrix,localFoldMatrix(f,out[f.parent].face,p)):translationMatrix(-f.width/2,-f.height/2,o.foldPlan.find(x=>x.id==="top").height/2);out[f.id]={face:f,matrix,points:[V(0,0,0),V(f.width,0,0),V(f.width,f.height,0),V(0,f.height,0)].map(q=>transformPoint(matrix,q))}});return out}
function corners(t){return t.points}
function pointKey(p){return`${Math.round(p.x/EPSILON)},${Math.round(p.y/EPSILON)},${Math.round(p.z/EPSILON)}`}
function faceNormal(points){const a=V(points[1].x-points[0].x,points[1].y-points[0].y,points[1].z-points[0].z),b=V(points[2].x-points[0].x,points[2].y-points[0].y,points[2].z-points[0].z),n=V(a.y*b.z-a.z*b.y,a.z*b.x-a.x*b.z,a.x*b.y-a.y*b.x),l=Math.hypot(n.x,n.y,n.z)||1;return V(n.x/l,n.y/l,n.z/l)}
function validateCompletedCuboid(faces,width,depth,height){const reasons=[],list=Object.values(faces);if(list.length!==6)reasons.push(`面数=${list.length}`);if(list.some(f=>f.points.length!==4))reasons.push("4頂点でない面があります");const unique=new Map(),edges=new Map();list.forEach(f=>{f.points.forEach(p=>unique.set(pointKey(p),p));for(let i=0;i<4;i++){const a=pointKey(f.points[i]),b=pointKey(f.points[(i+1)%4]),key=[a,b].sort().join("|");edges.set(key,(edges.get(key)||0)+1)}});if(unique.size!==8)reasons.push(`頂点種類=${unique.size}`);if(edges.size!==12)reasons.push(`辺種類=${edges.size}`);if([...edges.values()].some(n=>n!==2))reasons.push("共有されていない辺があります");const pts=[...unique.values()],span=axis=>Math.max(...pts.map(p=>p[axis]))-Math.min(...pts.map(p=>p[axis]));if(Math.abs(span("x")-width)>EPSILON||Math.abs(span("y")-height)>EPSILON||Math.abs(span("z")-depth)>EPSILON)reasons.push(`寸法=${span("x").toFixed(3)}×${span("z").toFixed(3)}×${span("y").toFixed(3)}`);const dirs=new Set(list.map(f=>{const n=faceNormal(f.points),a=[[Math.abs(n.x),n.x>0?"+x":"-x"],[Math.abs(n.y),n.y>0?"+y":"-y"],[Math.abs(n.z),n.z>0?"+z":"-z"]].sort((q,r)=>r[0]-q[0])[0];return a[0]>.999?a[1]:"斜め"}));if(dirs.size!==6||dirs.has("斜め"))reasons.push(`法線=${[...dirs].join(",")}`);return{valid:reasons.length===0,reasons,vertices:unique.size,edges:edges.size}}
function maxHingeGap(faces){const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y,a.z-b.z);let max=0;Object.values(faces).filter(f=>f.face.parent).forEach(c=>{const p=faces[c.face.parent],e=c.face.hingeEdge;let pe,ce;if(e==="top"){pe=[p.points[0],p.points[1]];ce=[c.points[3],c.points[2]]}if(e==="right"){pe=[p.points[1],p.points[2]];ce=[c.points[0],c.points[3]]}if(e==="bottom"){pe=[p.points[3],p.points[2]];ce=[c.points[0],c.points[1]]}if(e==="left"){pe=[p.points[0],p.points[3]];ce=[c.points[1],c.points[2]]}max=Math.max(max,Math.min(Math.max(dist(pe[0],ce[0]),dist(pe[1],ce[1])),Math.max(dist(pe[0],ce[1]),dist(pe[1],ce[0]))))});return max}
function cameraMatrix(spin=0){return multiplyMatrices(rotationAroundAxisMatrix(V(0,0,0),V(1,0,0),-25*Math.PI/180),rotationAroundAxisMatrix(V(0,0,0),V(0,1,0),(35*Math.PI/180)+spin))}
function project(v,s,cx,cy){const k=28/(28-v.z);return{x:cx+v.x*s*k,y:cy+v.y*s*k}}
function buildFold(o){app.activeOption=o;const svg=svgEl("svg",{viewBox:"0 0 760 420",preserveAspectRatio:"xMidYMid meet",class:"fold-svg",role:"img","aria-label":"6面を折りたたむ様子"});IDS.forEach(id=>{svg.append(svgEl("polygon",{class:"fold-face",fill:COLORS[id],"data-face":id}));const t=svgEl("text",{class:"fold-label","data-label":id});t.textContent=NAMES[id];svg.append(t)});$("#foldStage").replaceChildren(svg);setFold(0)}
function renderFold(p,spin=0){const o=app.activeOption;if(!o)return;const limited=o.correct?p:Math.min(p,o.failureProgress),faces=calculate(o,limited);document.documentElement.dataset.hingeGap=maxHingeGap(faces).toFixed(6);const camera=limited<.001?identityMatrix():cameraMatrix(spin),rendered=Object.values(faces).map(f=>{const cameraPoints=f.points.map(v=>transformPoint(camera,v)),normal=faceNormal(cameraPoints);return{...f,cameraPoints,normal,averageDepth:cameraPoints.reduce((s,q)=>s+q.z,0)/4}}),all=rendered.flatMap(f=>f.cameraPoints),rx=Math.max(...all.map(v=>v.x))-Math.min(...all.map(v=>v.x))||1,ry=Math.max(...all.map(v=>v.y))-Math.min(...all.map(v=>v.y))||1,s=Math.min(560/rx,300/ry,64),cx=380-(Math.max(...all.map(v=>v.x))+Math.min(...all.map(v=>v.x)))/2*s,cy=210-(Math.max(...all.map(v=>v.y))+Math.min(...all.map(v=>v.y)))/2*s,fail=!o.correct&&p>=o.failureProgress-.001,complete=o.correct&&limited>.995;rendered.sort((a,b)=>a.averageDepth-b.averageDepth).forEach(f=>{const visible=!complete||f.normal.z>EPSILON,pts=f.cameraPoints.map(v=>project(v,s,cx,cy)),poly=$(`[data-face="${f.face.id}"]`);poly.style.display=visible?"":"none";poly.setAttribute("points",pts.map(q=>`${q.x.toFixed(1)},${q.y.toFixed(1)}`).join(" "));poly.parentNode.append(poly);poly.classList.toggle("error",fail&&o.errorFaces.includes(f.face.id));const label=$(`[data-label="${f.face.id}"]`),c=pts.reduce((a,q)=>({x:a.x+q.x/4,y:a.y+q.y/4}),{x:0,y:0});label.style.display=visible&&app.settings.faces?"block":"none";label.setAttribute("x",c.x);label.setAttribute("y",c.y);label.parentNode.append(label)});if(fail)$("#explanation").textContent=o.explanation}
function setFold(v){app.progress=Number(v)/100;$("#animSlider").value=Math.round(app.progress*100);renderFold(app.progress)}function play(){clearInterval(app.timer);app.spin=0;if(matchMedia("(prefers-reduced-motion: reduce)").matches){setFold((app.activeOption.correct?1:app.activeOption.failureProgress)*100);return}app.timer=setInterval(()=>{const stop=app.activeOption.correct?1:app.activeOption.failureProgress;if(app.progress<stop){app.progress=Math.min(stop,app.progress+.012);$("#animSlider").value=Math.round(app.progress*100);renderFold(app.progress);return}if(!app.activeOption.correct){clearInterval(app.timer);return}app.spin+=.035;renderFold(1,Math.sin(app.spin)*.28)},35)}
function finish(){clearInterval(app.timer);show("resultScreen");const total=app.questions.length,p=Math.round(app.correct/total*100),wrong=total-app.correct;$("#scorePercent").textContent=`${p}%`;$("#scoreRing").style.setProperty("--score",`${p}%`);$("#resultStats").innerHTML=`<span>問題数 ${total}</span><span>正解 ${app.correct}</span><span>間違い ${wrong}</span>`;$("#evaluation").textContent=p===100?"全問正解！":p>=80?"よくできました！":p>=50?"あと少し！":"もう一度挑戦しよう！";$("#reviewBtn").hidden=wrong===0;$("#reviewDone").hidden=!app.review;tone("finish")}function tone(k){if(!$("#soundToggle").checked)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=k==="finish"?523:k?660:210;g.gain.setValueAtTime(.08,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.25);o.start();o.stop(c.currentTime+.26)}catch(e){}}
$("#startBtn").onclick=()=>begin();$("#settingsBtn").onclick=()=>show("settingsScreen");$("#saveSettingsBtn").onclick=()=>{app.settings={count:Number(val("count")),level:val("level"),lengths:$("#lengthToggle").checked,faces:$("#faceToggle").checked};begin()};$$('.home-btn').forEach(b=>b.onclick=()=>{clearInterval(app.timer);show("homeScreen")});$("#nextBtn").onclick=()=>{if(++app.index>=app.questions.length)finish();else renderQuestion()};$("#retryBtn").onclick=()=>begin();$("#reviewBtn").onclick=()=>begin(app.mistakes);$("#playBtn").onclick=play;$("#pauseBtn").onclick=()=>clearInterval(app.timer);$("#resetAnimBtn").onclick=()=>{clearInterval(app.timer);setFold(0)};$("#animSlider").oninput=e=>{clearInterval(app.timer);setFold(e.target.value)};$("#showCorrectBtn").onclick=()=>{const o=app.questions[app.index].options.find(x=>x.correct);$("#animationMessage").textContent="正しい展開図を組み立てます";$("#explanation").textContent=o.explanation;$("#showCorrectBtn").hidden=true;buildFold(o);play()};$("#rubyToggle").onchange=e=>document.body.classList.toggle("ruby-on",e.target.checked);$("#fullscreenBtn").onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();show("homeScreen");
